services:
  - type: web
    name: huyehomes
    env: static
    buildCommand: echo "No build command needed"
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
